### ISSUE TITLE
Is it possible to just enable Visa and Mastercard

### ISSUE THREAD

**Issue by StefanRu1** [wirecard/oxid-ee#200]
Hi,

i tried to configure it via OXID but this does not work.
Even if i select only VISA and MASTERCARD the wircard plugin offers all cards.

Is it possible to exclude all other cards except VISA and MASTERCARD in the Wirecardplugin?

Thanks and bets regards,
Stefan

**Comment by tomazpu** [comment]
Hello,

in the plugin itself it is not possible to configure that, but when the account for you is created this restrictions are done with the configuration. 

For more information contact are support at shop-systems-support@wirecard.com

Best regards, 
Tomaz
