### ISSUE TITLE
No Issue but question

### ISSUE THREAD

**Issue by maexware-stefan** [wirecard/oxid-ee#34]
Hi,
is this module already usable or still in development?
recognize much movement in the code, and a short test was not successfull.

Note: Checked the pull requests and took a look at the code, it seems not finished yet, is there a release date ?

Regards Stefan

**Comment by jakubpolomsky** [comment]
Hi,

it is still a work in progress. ETA for release is not settled yet. Keep an eye on the repo. The first release will be a very usable MVP

Kind regards,
Wirecard
